### ISSUE TITLE
added GIF

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/ionic-accordion-component#1]
![ionic-accordian](https://user-images.githubusercontent.com/6559664/50391910-9a1f0800-076f-11e9-97c3-52b98c0f88a2.gif)

**Comment by thamaraiselvam** [comment]
![ionic-accordion](https://user-images.githubusercontent.com/6559664/50392144-c3d92e80-0771-11e9-9fec-c4d9c8f8d962.gif)

**Comment by thamaraiselvam** [comment]
![ionic-accordion](https://user-images.githubusercontent.com/6559664/50392565-8b3b5400-0775-11e9-8561-a43d797d6b6e.gif)

**Comment by Noext** [comment]
can you provied a example for this ? if i make multiple accordion they dont toggle together
